# Generated by Django 2.2.28 on 2022-07-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0133_auto_20220725_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='seen_by',
        ),
    ]
